# Generated by Django 4.1.1 on 2022-11-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_conexao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='materiais',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('disciplina', models.ManyToManyField(to='first.disciplina')),
            ],
        ),
    ]
